#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/database
- name: Run Database Container
  docker_container:
    name: my-database
    image: iamjuli3n78/tp-devops-database:latest
    networks:
      - name: app-network
    env:
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_password }}"
      POSTGRES_DB: "{{ db_name }}"
    restart_policy: always
