services:
  backend:
    build: ./simpleapi
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - frontend-network
      - backend-network
    depends_on:
      - database
    environment:
      - USER_DB_URL=${USER_DB_URL}
      - USER_DB=${USER_DB}
      - USER_DB_PASSWORD=${USER_DB_PASSWORD}

  database:
    build: ./new_app
    restart: unless-stopped
    networks:
      - backend-network
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - USER_DB_URL=${USER_DB_URL}
      - USER_DB=${USER_DB}
      - USER_DB_PASSWORD=${USER_DB_PASSWORD}

  httpd:
    build: ./hhtp_server
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - frontend-network
    depends_on:
      - backend
    environment:
    - BACKEND_URL=${BACKEND_URL}

networks:
  frontend-network:
  backend-network:

volumes:
  db-data: