#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/app
- name: Run Backend Applications (Redundancy)
  docker_container:
    name: "{{ item }}"
    image: "{{ docker_username }}/tp-devops-simple-api:latest"
    pull: true
    recreate: true
    networks:
      - name: app-network
    env:
      USER_DB_URL: "jdbc:postgresql://my-database:5432/{{ db_name }}"
      USER_DB: "{{ db_user }}"
      USER_DB_PASSWORD: "{{ db_password }}"
    restart_policy: always
  loop:
    - backend-blue
    - backend-green