- hosts: all
  gather_facts: true
  become: true

  roles:
    - docker
    - network
    - database
    - app
    - proxy

  post_tasks:
    - name: Run Frontend Container
      community.docker.docker_container:
        name: my-frontend
        image: "{{ docker_username }}/tp-devops-frontend:latest"
        pull: true
        recreate: true
        state: started
        restart_policy: always
        networks:
          - name: app-network
        exposed_ports:
          - "80"