#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/proxy
- name: Run HTTPD Proxy
  docker_container:
    name: my-proxy
    image: iamjuli3n78/tp-devops-httpd:latest
    pull: true
    recreate: true
    networks:
      - name: app-network
    ports:
      - "80:80"
    env:
      BACKEND_URL: "http://my-app:8080"
      FRONTEND_URL: "my-frontend"
    restart_policy: always
