name: Continuous Delivery (CD)

on:
  workflow_run:
    workflows: ["Continuous Integration (CI)"] # Écoute le fichier CI pour déclencher ce workflow CD
    types:
      - completed
    branches:
      - main
jobs:
  build-and-push-docker-image:
    if:  >
      github.event.workflow_run.conclusion == 'success' && 
      (github.event.workflow_run.head_branch == 'main')
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_BEARER }}

      # 1. Le Backend
      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./simpleapi
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-simple-api:latest

      # 2. La Database
      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./new_app 
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-database:latest

      # 3. Le serveur HTTPD
      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./hhtp_server
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-httpd:latest

      # 4. Le Frontend 
      - name: Build image and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./devops-front-main # Mets le nom exact de ton dossier front
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-frontend:latest


  deploy-application:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image # Ne se lance que si les images ont bien été poussées
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Deploy using Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          # 1. On extrait la clé SSH
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
          # On injecte les secrets en tant que variables Ansible (-e)
          ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml \
            --private-key=private_key.pem -u admin \
            -e "db_name=${{ secrets.DB_NAME }} \
                db_user=${{ secrets.DB_USER }} \
                db_password=${{ secrets.DB_PASSWORD }}"