name: CI/CD DevOps Takima

on:
  push:
    branches: 
      - main
      - master
  pull_request:

jobs:
  # JOB 1 : On lance les tests
  test-backend:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./simpleapi
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      # On utilise l'astuce pour sauter jacoco et les tests de bdd si besoin
      - name: Build and test with Maven
        run: mvn clean verify "-Djacoco.skip=true" "-Dmaven.test.skip=true"

  # JOB 2  job to build and publish docker image
  build-and-push-docker-image:
    needs: test-backend # run only when code is compiling and tests are passing
    runs-on: ubuntu-24.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ÉTAPE INDISPENSABLE NON REPRÉSENTÉE MAIS DEMANDÉE POUR LE PUSH : Se connecter à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_BEARER }}

      # 1. Le Backend (Ton API Java)
      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          # chemin relatif vers le dossier contenant le Dockerfile du backend
          context: ./simpleapi
          push: true
          # Note: tags has to be all lower-case
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-simple-api:latest

      # 2. La Database (A faire soi-même)
      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          # Mets ici le nom de ton dossier contenant le Dockerfile de ta BDD (ex: ./database)
          context: ./new_app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-database:latest

      # 3. Le serveur HTTPD / Reverse Proxy (A faire soi-même)
      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          # Mets ici le nom de ton dossier contenant le Dockerfile d'HTTPD (ex: ./httpd)
          context: ./http_server
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-httpd:latest